### ISSUE TITLE
Error in ng build --prod

### ISSUE THREAD

**Issue by ViniciusAlberkovics** [thekip/angular-cc-library#68]
the package is showing the error below to build --prod in version of angular 8.2.0.
Below the error and package.json information.

Package.json:
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/cdk": "~7.3.5",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^7.3.5",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "angular-cc-library": "^2.0.1",
    "angular-form-builder": "^0.1.9",
    "angular-web-storage": "^9.0.0",
    "bootstrap": "^4.4.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "ngx-card": "^0.2.4",
    "ngx-mask": "^8.1.7",
    "ngx-slick-carousel": "^0.4.7",
    "popper.js": "^1.16.1",
    "rxjs": "~6.4.0",
    "slick-carousel": "^1.8.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "~8.2.0",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }

Error:
ERROR in ./node_modules/angular-cc-library/fesm2015/angular-cc-library.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\projects\88i\Site\oito-i\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\projects\88i\Site\oito-i\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:16631:30)
    at Object.forEachChild (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:16859:24)
    at transformer (C:\projects\88i\Site\oito-i\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:63:16)    
    at transformSourceFileOrBundle (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:67384:57)
    at transformation (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:83586:24)
    at transformRoot (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:83606:82)
    at Object.map (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:499:29)
    at Object.transformNodes (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:83593:30)
    at emitJsFileOrBundle (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:84089:32)
    at emitSourceFileOrBundle (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:84043:13)
    at forEachEmittedFile (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:83832:34)
    at Object.emitFiles (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:84026:9)
    at emitWorker (C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:89951:33)
    at C:\projects\88i\Site\oito-i\node_modules\typescript\lib\typescript.js:89912:66

**Comment by thekip** [comment]
The library was generated and built with AngularCli 9. Theoretically, it should be backward compatible, but how we see it's not. 

You can use 1.* version for Angular versions prior 9, and 2.* for Angular 9 with Ivy.

**Comment by ViniciusAlberkovics** [comment]
I managed to resolve or error when changing a version of the package @ angular-devkit / build-angular

I made the change to the version below
**"@angular-devkit/build-angular": "~0.803.20"**
